import matplotlib.pyplot as plt
import matplotlib.ticker as mtick 
from matplotlib.ticker import PercentFormatter 
from matplotlib.ticker import FormatStrFormatter
import math
import numpy as np

# Plot input
plt.rcParams['figure.figsize'] = [4, 4]
plt.rcParams["font.family"] = "Times New Roman"
plt.style.use('ggplot')
plt.rc('xtick', labelsize=8) 
plt.rc('ytick', labelsize=8) 
font = {'family' : 'Times New Roman',
        'weight' : 'normal',
        'size'   : 8}
plt.rc('legend', fontsize=8) #14
plt.rcParams['legend.title_fontsize'] = 8 #16
plt.rc('font', **font)

def plot_multi_graph(res_scn, vals):
    fig, axes = plt.subplots(7, 6, figsize = [24,18])
    # plt.subplots_adjust(top=.9, bottom=.1, hspace=.1, left=.1, right=.9, wspace=.1)
    fig.subplots_adjust(hspace=.5, wspace=0.4, left=.12, right=.88)
    plt.setp(axes, xlim=[0,200])
    
    axes[0, 0].plot(res_scn.sup.inform)
    axes[0, 0].set_ylabel('Informed driver agents')
    axes[0, 0].set_xlabel('Day')
    axes[0, 0].set_title('(a)')
    axes[0, 0].set_ylim(bottom = 0, top = res_scn.sup.inform.max().max() + 25)
    axes[0, 0].locator_params(axis='y', nbins=5)

    axes[0, 1].plot(res_scn.sup.regist)
    axes[0, 1].set_ylabel('Registered drivers')
    axes[0, 1].set_xlabel('Day')
    axes[0, 1].set_title('(b)')
    axes[0, 1].set_ylim(bottom = 0, top = math.ceil(res_scn.sup.regist.max().max()/100)*100+50)
    axes[0, 1].set_xlim(left = 0, right = 200)
    axes[0, 1].locator_params(axis='y', nbins=5)

    axes[0, 2].plot(res_scn.sup.particip)
    axes[0, 2].set_ylabel('Participating drivers')
    axes[0, 2].set_xlabel('Day')
    axes[0, 2].set_title('(c)')
    axes[0, 2].set_ylim(bottom = 0, top = math.ceil(res_scn.sup.particip.max().max()/100)*100+50)
    axes[0, 2].set_xlim(left = 0, right = 200)
    axes[0, 2].locator_params(axis='y', nbins=5)

    axes[0, 3].plot(res_scn.sup.mean_perc_inc)
    axes[0, 3].set_ylabel('Expected income of \n inf. driver agents (€)')
    axes[0, 3].set_xlabel('Day')
    axes[0, 3].set_title('(d)')
    axes[0, 3].set_ylim(bottom = 0, top = math.ceil(res_scn.sup.mean_perc_inc.max().max()*1.2/0.5)*0.5)
    axes[0, 3].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))
    axes[0, 3].locator_params(axis='y', nbins=5)

    axes[0, 4].plot(res_scn.sup.mean_perc_inc_reg)
    axes[0, 4].set_ylabel('Expected income of \n reg. driver agents (€)')
    axes[0, 4].set_xlabel('Day')
    axes[0, 4].set_title('(e)')
    axes[0, 4].set_ylim(bottom = 0, top = math.ceil(res_scn.sup.mean_perc_inc_reg.max().max()*1.2/0.5)*0.5)
    axes[0, 4].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))
    axes[0, 4].locator_params(axis='y', nbins=5)

    axes[0, 5].plot(res_scn.sup.mean_perc_inc_ptcp)
    axes[0, 5].set_ylabel('Expected income of \n part. driver agents (€)')
    axes[0, 5].set_xlabel('Day')
    axes[0, 5].set_title('(f)')
    axes[0, 5].set_ylim(bottom = 0, top = math.ceil(res_scn.sup.mean_perc_inc_ptcp.max().max()*1.2/0.5)*0.5)
    axes[0, 5].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))
    axes[0, 5].locator_params(axis='y', nbins=5)

    axes[1, 0].plot(res_scn.sup.mean_exp_inc)
    axes[1, 0].set_ylabel('Experienced income (€)')
    axes[1, 0].set_xlabel('Day')
    axes[1, 0].set_title('(g)')
    axes[1, 0].set_ylim(bottom = 0, top = math.ceil(res_scn.sup.mean_exp_inc.max().max()*1.2/0.5)*0.5)
    axes[1, 0].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))
    axes[1, 0].locator_params(axis='y', nbins=5)

    axes[1, 1].plot(res_scn.sup.rel_perc_inc)
    axes[1, 1].set_ylabel('Expected income of inf. drivers \n rel. to their res. wage')
    axes[1, 1].set_xlabel('Day')
    axes[1, 1].set_title('(h)')
    axes[1, 1].set_ylim(bottom = 0, top = math.ceil(res_scn.sup.rel_perc_inc.max().max()*1.2/0.5)*0.5)
    axes[1, 1].yaxis.set_major_formatter(FormatStrFormatter('%.1f'))
    axes[1, 1].locator_params(axis='y', nbins=5)

    axes[1, 2].plot(res_scn.sup.rel_perc_inc_reg)
    axes[1, 2].set_ylabel('Expected income of reg. drivers \n rel. to their res. wage')
    axes[1, 2].set_xlabel('Day')
    axes[1, 2].set_title('(i)')
    axes[1, 2].set_ylim(bottom = 0, top = math.ceil(res_scn.sup.rel_perc_inc_reg.max().max()*1.2/0.5)*0.5)
    axes[1, 2].yaxis.set_major_formatter(FormatStrFormatter('%.1f'))
    axes[1, 2].locator_params(axis='y', nbins=5)

    axes[1, 3].plot(res_scn.sup.rel_perc_inc_ptcp)
    axes[1, 3].set_ylabel('Expected income of part. drivers \n rel. to their res. wage')
    axes[1, 3].set_xlabel('Day')
    axes[1, 3].set_title('(j)')
    axes[1, 3].set_ylim(bottom = 0, top = math.ceil(res_scn.sup.rel_perc_inc_ptcp.max().max()*1.2/0.5)*0.5)
    axes[1, 3].yaxis.set_major_formatter(FormatStrFormatter('%.1f'))
    axes[1, 3].locator_params(axis='y', nbins=5)

    axes[1, 4].plot(res_scn.sup.std_perc_inc)
    axes[1, 4].set_ylabel('St. dev. of expected income \n of inf. drivers (€)')
    axes[1, 4].set_xlabel('Day')
    axes[1, 4].set_title('(k)')
    axes[1, 4].set_ylim(bottom = 0, top = math.ceil(res_scn.sup.std_perc_inc.max().max()*1.2/0.5)*0.5)
    axes[1, 4].yaxis.set_major_formatter(FormatStrFormatter('%.1f'))
    axes[1, 4].locator_params(axis='y', nbins=5)

    axes[1, 5].plot(res_scn.sup.std_perc_inc_reg)
    axes[1, 5].set_ylabel('St. dev. of expected income \n of reg. drivers (€)')
    axes[1, 5].set_xlabel('Day')
    axes[1, 5].set_title('(l)')
    axes[1, 5].set_ylim(bottom = 0, top = math.ceil(res_scn.sup.std_perc_inc_reg.max().max()*1.2/0.5)*0.5)
    axes[1, 5].yaxis.set_major_formatter(FormatStrFormatter('%.1f'))
    axes[1, 5].locator_params(axis='y', nbins=5)

    axes[2, 0].plot(res_scn.sup.std_perc_inc_ptcp)
    axes[2, 0].set_ylabel('St. dev. of expected income \n of inf. drivers (€)')
    axes[2, 0].set_xlabel('Day')
    axes[2, 0].set_title('(m)')
    axes[2, 0].set_ylim(bottom = 0, top = math.ceil(res_scn.sup.std_perc_inc_ptcp.max().max()*1.2/0.5)*0.5)
    axes[2, 0].yaxis.set_major_formatter(FormatStrFormatter('%.1f'))
    axes[2, 0].locator_params(axis='y', nbins=5)

    axes[2, 1].plot(res_scn.sup.res_wage_inf)
    axes[2, 1].set_ylabel('Mean res. wage \n of informed drivers (€)')
    axes[2, 1].set_xlabel('Day')
    axes[2, 1].set_title('(n)')
    axes[2, 1].set_ylim(bottom = 0, top = math.ceil(res_scn.sup.res_wage_inf.max().max()*1.2/0.5)*0.5)
    axes[2, 1].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))
    axes[2, 1].locator_params(axis='y', nbins=5)

    axes[2, 2].plot(res_scn.sup.res_wage_reg)
    axes[2, 2].set_ylabel('Mean res. wage \n of regist. drivers (€)')
    axes[2, 2].set_xlabel('Day')
    axes[2, 2].set_title('(o)')
    axes[2, 2].set_ylim(bottom = 0, top = math.ceil(res_scn.sup.res_wage_reg.max().max()*1.2/0.5)*0.5)
    axes[2, 2].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))
    axes[2, 2].locator_params(axis='y', nbins=5)

    axes[2, 3].plot(res_scn.sup.res_wage_ptcp)
    axes[2, 3].set_ylabel('Mean res. wage \n of part. drivers (€)')
    axes[2, 3].set_xlabel('Day')
    axes[2, 3].set_title('(p)')
    axes[2, 3].set_ylim(bottom = 0, top = math.ceil(res_scn.sup.res_wage_ptcp.max().max()*1.2/0.5)*0.5)
    axes[2, 3].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))
    axes[2, 3].locator_params(axis='y', nbins=5)

    axes[2, 4].plot(res_scn.sup.driver_surplus)
    axes[2, 4].set_ylabel('Driver surplus (€)')
    axes[2, 4].set_xlabel('Day')
    axes[2, 4].set_title('(q)')
    axes[2, 4].set_ylim(bottom = math.floor(res_scn.sup.driver_surplus.min().min()*0.8/0.5)*0.5, top = math.ceil(res_scn.sup.driver_surplus.max().max()*1.2/0.5)*0.5)
    axes[2, 4].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))
    axes[2, 4].locator_params(axis='y', nbins=5)

    axes[2, 5].plot(res_scn.sup.new_regist)
    axes[2, 5].set_ylabel('New daily registrations')
    axes[2, 5].set_xlabel('Day')
    axes[2, 5].set_title('(r)')
    axes[2, 5].set_ylim(bottom = 0, top = math.ceil(res_scn.sup.new_regist.max().max()*1.2/0.5)*0.5)
    axes[2, 5].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))
    axes[2, 5].locator_params(axis='y', nbins=5)

    axes[3, 0].plot(res_scn.sup.deregist)
    axes[3, 0].set_ylabel('Daily deregistrations')
    axes[3, 0].set_xlabel('Day')
    axes[3, 0].set_title('(s)')
    axes[3, 0].set_ylim(bottom = 0, top = math.ceil(res_scn.sup.deregist.max().max()*1.2/0.5)*0.5)
    axes[3, 0].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))
    axes[3, 0].locator_params(axis='y', nbins=5)

    axes[3, 1].plot(res_scn.dem.inform)
    axes[3, 1].set_ylabel('Informed travellers')
    axes[3, 1].set_xlabel('Day')
    axes[3, 1].set_title('(s)')
    axes[3, 1].set_ylim(bottom = 0, top = math.ceil(res_scn.dem.inform.max().max()*1.2/0.5)*0.5)
    axes[3, 1].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))
    axes[3, 1].locator_params(axis='y', nbins=5)

    axes[3, 2].plot(res_scn.dem.requests)
    axes[3, 2].set_ylabel('Ride-hailing requests')
    axes[3, 2].set_xlabel('Day')
    axes[3, 2].set_title('(t)')
    axes[3, 2].set_ylim(bottom = 0, top = res_scn.dem.requests.max().max() + 50)
    # axes[0, 2].set_ylim(bottom = 0, top = math.ceil(res_scn.requests.max().max()*1.2/50)*50+100)
    axes[3, 2].locator_params(axis='y', nbins=5)

    axes[3, 3].plot(res_scn.dem.gets_offer)
    axes[3, 3].set_ylabel('Service rate')
    axes[3, 3].yaxis.set_major_formatter(mtick.PercentFormatter(1))  
    axes[3, 3].set_xlabel('Day')
    axes[3, 3].set_title('(u)')
    axes[3, 3].locator_params(axis='y', nbins=5)

    axes[3, 4].plot((res_scn.dem.perc_wait/60))
    axes[3, 4].set_ylabel('Expected waiting time \n of inf. travellers (min)')
    axes[3, 4].set_xlabel('Day')
    axes[3, 4].set_title('(v)')
    axes[3, 4].set_ylim(bottom = 0, top = math.ceil((res_scn.dem.perc_wait/60).max().max()*1.1/1)*1)
    axes[3, 4].set_yticks(np.arange(0, math.ceil((res_scn.dem.perc_wait/60).max().max()*1.1/1)*1+2, step=4))
    axes[3, 4].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))

    axes[3, 5].plot((res_scn.dem.corr_mean_wait/60))
    axes[3, 5].set_ylabel('Expected (corrected) \n waiting time of inf. trav. (min)')
    axes[3, 5].set_xlabel('Day')
    axes[3, 5].set_title('(w)')
    axes[3, 5].set_ylim(bottom = 0, top = math.ceil((res_scn.dem.corr_mean_wait/60).max().max()*1.1/1)*1)
    axes[3, 5].set_yticks(np.arange(0, math.ceil((res_scn.dem.corr_mean_wait/60).max().max()*1.1/1)*1+2, step=4))
    axes[3, 5].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))

    axes[4, 0].plot((res_scn.dem.perc_wait_req/60))
    axes[4, 0].set_ylabel('Expected waiting time \n of trav. opting for RS (min)')
    axes[4, 0].set_xlabel('Day')
    axes[4, 0].set_title('(x)')
    axes[4, 0].set_ylim(bottom = 0, top = math.ceil((res_scn.dem.perc_wait_req/60).max().max()*1.1/1)*1)
    axes[4, 0].set_yticks(np.arange(0, math.ceil((res_scn.dem.perc_wait_req/60).max().max()*1.1/1)*1+2, step=4))
    axes[4, 0].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))

    axes[4, 1].plot((res_scn.dem.mean_wait/60))
    axes[4, 1].set_ylabel('Experienced waiting time (min)')
    axes[4, 1].set_xlabel('Day')
    axes[4, 1].set_title('(y)')
    axes[4, 1].set_ylim(bottom = 0, top = math.ceil((res_scn.dem.mean_wait/60).max().max()*1.1/1)*1)
    axes[4, 1].set_yticks(np.arange(0, math.ceil((res_scn.dem.mean_wait/60).max().max()*1.1/1)*1+2, step=4))
    axes[4, 1].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))

    axes[4, 2].plot(res_scn.dem.bike / (res_scn.dem.requests + res_scn.dem.bike + res_scn.dem.car + res_scn.dem.pt))
    axes[4, 2].set_ylabel('Share of travellers \n choosing bike')
    axes[4, 2].yaxis.set_major_formatter(mtick.PercentFormatter(1))  
    axes[4, 2].set_xlabel('Day')
    axes[4, 2].set_title('(z)')
    axes[4, 2].locator_params(axis='y', nbins=5)

    axes[4, 3].plot(res_scn.dem.car / (res_scn.dem.requests + res_scn.dem.bike + res_scn.dem.car + res_scn.dem.pt))
    axes[4, 3].set_ylabel('Share of travellers \n choosing private car')
    axes[4, 3].yaxis.set_major_formatter(mtick.PercentFormatter(1))  
    axes[4, 3].set_xlabel('Day')
    axes[4, 3].set_title('(aa)')
    axes[4, 3].locator_params(axis='y', nbins=5)

    axes[4, 4].plot(res_scn.dem.pt / (res_scn.dem.requests + res_scn.dem.bike + res_scn.dem.car + res_scn.dem.pt))
    axes[4, 4].set_ylabel('Share of travellers \n choosing public transp.')
    axes[4, 4].yaxis.set_major_formatter(mtick.PercentFormatter(1))  
    axes[4, 4].set_xlabel('Day')
    axes[4, 4].set_title('(ab)')
    axes[4, 4].locator_params(axis='y', nbins=5)

    axes[4, 5].plot(res_scn.dem.vot_inf)
    axes[4, 5].set_ylabel('Mean value of time \n of inf. travellers (€/h)') 
    axes[4, 5].set_xlabel('Day')
    axes[4, 5].set_title('(ac)')
    axes[4, 5].set_ylim(bottom = 0, top = math.ceil(res_scn.dem.vot_inf.max().max()*1.1/1)*1)
    axes[4, 5].set_yticks(np.arange(0, math.ceil(res_scn.dem.vot_inf.max().max()*1.1/1)*1+2, step=4))
    axes[4, 5].locator_params(axis='y', nbins=5)

    axes[5, 0].plot(res_scn.dem.vot_req)
    axes[5, 0].set_ylabel('Mean value of time \n of trav. opting for RS (€/h)') 
    axes[5, 0].set_xlabel('Day')
    axes[5, 0].set_title('(ad)')
    axes[5, 0].set_ylim(bottom = 0, top = math.ceil(res_scn.dem.vot_req.max().max()*1.1/1)*1)
    axes[5, 0].set_yticks(np.arange(0, math.ceil(res_scn.dem.vot_req.max().max()*1.1/1)*1+2, step=4))
    axes[5, 0].locator_params(axis='y', nbins=5)

    axes[5, 1].plot(res_scn.dem.std_perc_wait / 60)
    axes[5, 1].set_ylabel('St. dev. of expected wait \n of inf. travellers (min)') 
    axes[5, 1].set_xlabel('Day')
    axes[5, 1].set_title('(ae)')
    axes[5, 1].set_ylim(bottom = 0, top = math.ceil(res_scn.dem.std_perc_wait.max().max()/60*1.1/1)*1)
    axes[5, 1].set_yticks(np.arange(0, math.ceil(res_scn.dem.std_perc_wait.max().max()/60*1.1/1)*1+2, step=4))
    axes[5, 1].locator_params(axis='y', nbins=5)

    axes[5, 2].plot(res_scn.dem.std_perc_wait_req / 60)
    axes[5, 2].set_ylabel('St. dev. of expected wait \n of trav. opting for RS (min)') 
    axes[5, 2].set_xlabel('Day')
    axes[5, 2].set_title('(af)')
    axes[5, 2].set_ylim(bottom = 0, top = math.ceil(res_scn.dem.std_perc_wait_req.max().max()/60*1.1/1)*1)
    axes[5, 2].set_yticks(np.arange(0, math.ceil(res_scn.dem.std_perc_wait_req.max().max()/60*1.1/1)*1+2, step=4))
    axes[5, 2].locator_params(axis='y', nbins=5)

    axes[5, 3].plot(res_scn.dem.std_exp_wait / 60)
    axes[5, 3].set_ylabel('St. dev. of experienced \n wait time (min)') 
    axes[5, 3].set_xlabel('Day')
    axes[5, 3].set_title('(af)')
    axes[5, 3].set_ylim(bottom = 0, top = math.ceil(res_scn.dem.std_exp_wait.max().max()/60*1.1/1)*1)
    axes[5, 3].set_yticks(np.arange(0, math.ceil(res_scn.dem.std_exp_wait.max().max()/60*1.1/1)*1+2, step=4))
    axes[5, 3].locator_params(axis='y', nbins=5)

    axes[5, 4].plot(res_scn.dem.cons_surplus)
    axes[5, 4].set_ylabel('Traveller surplus (€)') 
    axes[5, 4].set_xlabel('Day')
    axes[5, 4].set_title('(ag)')
    axes[5, 4].set_ylim(bottom = math.floor(res_scn.dem.cons_surplus.min().min()*0.9/1)*1, top = math.ceil(res_scn.dem.cons_surplus.max().max()*1.1/1)*1)
    axes[5, 4].set_yticks(np.arange(math.floor(res_scn.dem.cons_surplus.min().min()*0.9/1)*1, math.ceil(res_scn.dem.cons_surplus.max().max()*1.1/1)*1+2, step=4))
    axes[5, 4].locator_params(axis='y', nbins=5)

    axes[5, 5].plot(res_scn.plf.plat_profit)
    axes[5, 5].set_ylabel('Platform profit (€)')
    axes[5, 5].set_xlabel('Day')
    axes[5, 5].set_title('(ah)')
    axes[5, 5].set_ylim(bottom = 0, top = math.ceil(res_scn.plf.plat_profit.max().max()*1.1/1)*1)

    res_scn.soc.tot_value = res_scn.plf.plat_profit + res_scn.sup.driver_surplus + res_scn.dem.cons_surplus
    axes[6, 0].plot(res_scn.soc.tot_value)
    axes[6, 0].set_ylabel('Societal value (€)')
    axes[6, 0].set_xlabel('Day')
    axes[6, 0].set_title('(ai)')
    axes[6, 0].set_ylim(bottom = math.floor(res_scn.soc.tot_value.min().min()*0.9/1)*1, top = math.ceil(res_scn.soc.tot_value.max().max()*1.1/1)*1)

    axes[6, 1].plot(res_scn.sup.regist / res_scn.sup.inform)
    axes[6, 1].set_ylabel('Share of inf. drivers \n that are registered')
    axes[6, 1].set_xlabel('Day')
    axes[6, 1].set_title('(aj)')
    axes[6, 1].yaxis.set_major_formatter(mtick.PercentFormatter(1)) 

    axes[6, 2].plot(res_scn.sup.particip / res_scn.sup.regist)
    axes[6, 2].set_ylabel('Share of reg. drivers \n participating')
    axes[6, 2].set_xlabel('Day')
    axes[6, 2].set_title('(ak)')
    axes[6, 2].yaxis.set_major_formatter(mtick.PercentFormatter(1))
    
    fig.legend(vals, loc='lower center',title=False) #bbox_to_anchor=(0.7, 0.5)
    
    return fig


def plot_multi_graph_runs(res_sup, res_dem):
    no_rows = 10
    no_cols = 4
    fig, axes = plt.subplots(no_rows, no_cols, figsize = [24,48])
    # plt.subplots_adjust(top=.9, bottom=.1, hspace=.1, left=.1, right=.9, wspace=.1)
    fig.subplots_adjust(hspace=.5, wspace=0.4, left=.12, right=.88)
    plt.setp(axes, xlim=[0,200])
    
    axes[0, 0].plot(res_sup.inform.drop(['stdev'], axis=1))
    axes[0, 0].set_ylabel('Informed driver agents', fontsize = 10)
    axes[0, 0].set_xlabel('Day', fontsize = 10)
    axes[0, 0].set_title('(a)')
    axes[0, 0].set_ylim(bottom = 0, top = res_sup.inform.max().max() + 25)
    axes[0, 0].locator_params(axis='y', nbins=5)

    axes[0, 1].plot(res_sup.regist.drop(['stdev'], axis=1))
    axes[0, 1].set_ylabel('Registered drivers')
    axes[0, 1].set_xlabel('Day')
    axes[0, 1].set_title('(b)')
    axes[0, 1].set_ylim(bottom = 0, top = math.ceil(res_sup.regist.max().max()/100)*100+50)
    axes[0, 1].set_xlim(left = 0, right = 200)
    axes[0, 1].locator_params(axis='y', nbins=5)

    axes[0, 2].plot(res_sup.particip.drop(['stdev'], axis=1))
    axes[0, 2].set_ylabel('Participating drivers')
    axes[0, 2].set_xlabel('Day')
    axes[0, 2].set_title('(c)')
    axes[0, 2].set_ylim(bottom = 0, top = math.ceil(res_sup.particip.max().max()/100)*100+50)
    axes[0, 2].set_xlim(left = 0, right = 200)
    axes[0, 2].locator_params(axis='y', nbins=5)

    axes[0, 3].plot(res_sup.mean_perc_inc.drop(['stdev'], axis=1))
    axes[0, 3].set_ylabel('Expected income of \n inf. driver agents (€)')
    axes[0, 3].set_xlabel('Day')
    axes[0, 3].set_title('(d)')
    axes[0, 3].set_ylim(bottom = 0, top = math.ceil(res_sup.mean_perc_inc.max().max()*1.2/0.5)*0.5)
    axes[0, 3].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))
    axes[0, 3].locator_params(axis='y', nbins=5)

    axes[1, 0].plot(res_sup.mean_perc_inc_reg.drop(['stdev'], axis=1))
    axes[1, 0].set_ylabel('Expected income of \n reg. driver agents (€)')
    axes[1, 0].set_xlabel('Day')
    axes[1, 0].set_title('(e)')
    axes[1, 0].set_ylim(bottom = 0, top = math.ceil(res_sup.mean_perc_inc_reg.max().max()*1.2/0.5)*0.5)
    axes[1, 0].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))
    axes[1, 0].locator_params(axis='y', nbins=5)

    axes[1, 1].plot(res_sup.mean_perc_inc_ptcp.drop(['stdev'], axis=1))
    axes[1, 1].set_ylabel('Expected income of \n part. driver agents (€)')
    axes[1, 1].set_xlabel('Day')
    axes[1, 1].set_title('(f)')
    axes[1, 1].set_ylim(bottom = 0, top = math.ceil(res_sup.mean_perc_inc_ptcp.max().max()*1.2/0.5)*0.5)
    axes[1, 1].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))
    axes[1, 1].locator_params(axis='y', nbins=5)

    axes[1, 2].plot(res_sup.mean_exp_inc.drop(['stdev'], axis=1))
    axes[1, 2].set_ylabel('Experienced income (€)')
    axes[1, 2].set_xlabel('Day')
    axes[1, 2].set_title('(g)')
    axes[1, 2].set_ylim(bottom = 0, top = math.ceil(res_sup.mean_exp_inc.max().max()*1.2/0.5)*0.5)
    axes[1, 2].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))
    axes[1, 2].locator_params(axis='y', nbins=5)

    axes[1, 3].plot(res_sup.rel_perc_inc.drop(['stdev'], axis=1))
    axes[1, 3].set_ylabel('Expected income of inf. drivers \n rel. to their res. wage')
    axes[1, 3].set_xlabel('Day')
    axes[1, 3].set_title('(h)')
    axes[1, 3].set_ylim(bottom = 0, top = math.ceil(res_sup.rel_perc_inc.max().max()*1.2/0.5)*0.5)
    axes[1, 3].yaxis.set_major_formatter(FormatStrFormatter('%.1f'))
    axes[1, 3].locator_params(axis='y', nbins=5)

    axes[2, 0].plot(res_sup.rel_perc_inc_reg.drop(['stdev'], axis=1))
    axes[2, 0].set_ylabel('Expected income of reg. drivers \n rel. to their res. wage')
    axes[2, 0].set_xlabel('Day')
    axes[2, 0].set_title('(i)')
    axes[2, 0].set_ylim(bottom = 0, top = math.ceil(res_sup.rel_perc_inc_reg.max().max()*1.2/0.5)*0.5)
    axes[2, 0].yaxis.set_major_formatter(FormatStrFormatter('%.1f'))
    axes[2, 0].locator_params(axis='y', nbins=5)

    axes[2, 1].plot(res_sup.rel_perc_inc_ptcp.drop(['stdev'], axis=1))
    axes[2, 1].set_ylabel('Expected income of part. drivers \n rel. to their res. wage')
    axes[2, 1].set_xlabel('Day')
    axes[2, 1].set_title('(j)')
    axes[2, 1].set_ylim(bottom = 0, top = math.ceil(res_sup.rel_perc_inc_ptcp.max().max()*1.2/0.5)*0.5)
    axes[2, 1].yaxis.set_major_formatter(FormatStrFormatter('%.1f'))
    axes[2, 1].locator_params(axis='y', nbins=5)

    axes[2, 2].plot(res_sup.std_perc_inc.drop(['stdev'], axis=1))
    axes[2, 2].set_ylabel('St. dev. of expected income \n of inf. drivers (€)')
    axes[2, 2].set_xlabel('Day')
    axes[2, 2].set_title('(k)')
    axes[2, 2].set_ylim(bottom = 0, top = math.ceil(res_sup.std_perc_inc.max().max()*1.2/0.5)*0.5)
    axes[2, 2].yaxis.set_major_formatter(FormatStrFormatter('%.1f'))
    axes[2, 2].locator_params(axis='y', nbins=5)

    axes[2, 3].plot(res_sup.std_perc_inc_reg.drop(['stdev'], axis=1))
    axes[2, 3].set_ylabel('St. dev. of expected income \n of reg. drivers (€)')
    axes[2, 3].set_xlabel('Day')
    axes[2, 3].set_title('(l)')
    axes[2, 3].set_ylim(bottom = 0, top = math.ceil(res_sup.std_perc_inc_reg.max().max()*1.2/0.5)*0.5)
    axes[2, 3].yaxis.set_major_formatter(FormatStrFormatter('%.1f'))
    axes[2, 3].locator_params(axis='y', nbins=5)

    axes[3, 0].plot(res_sup.std_perc_inc_ptcp.drop(['stdev'], axis=1))
    axes[3, 0].set_ylabel('St. dev. of expected income \n of inf. drivers (€)')
    axes[3, 0].set_xlabel('Day')
    axes[3, 0].set_title('(m)')
    axes[3, 0].set_ylim(bottom = 0, top = math.ceil(res_sup.std_perc_inc_ptcp.max().max()*1.2/0.5)*0.5)
    axes[3, 0].yaxis.set_major_formatter(FormatStrFormatter('%.1f'))
    axes[3, 0].locator_params(axis='y', nbins=5)

    axes[3, 1].plot(res_sup.res_wage_inf.drop(['stdev'], axis=1))
    axes[3, 1].set_ylabel('Mean res. wage \n of informed drivers (€)')
    axes[3, 1].set_xlabel('Day')
    axes[3, 1].set_title('(n)')
    axes[3, 1].set_ylim(bottom = 0, top = math.ceil(res_sup.res_wage_inf.max().max()*1.2/0.5)*0.5)
    axes[3, 1].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))
    axes[3, 1].locator_params(axis='y', nbins=5)

    axes[3, 2].plot(res_sup.res_wage_reg.drop(['stdev'], axis=1))
    axes[3, 2].set_ylabel('Mean res. wage \n of regist. drivers (€)')
    axes[3, 2].set_xlabel('Day')
    axes[3, 2].set_title('(o)')
    axes[3, 2].set_ylim(bottom = 0, top = math.ceil(res_sup.res_wage_reg.max().max()*1.2/0.5)*0.5)
    axes[3, 2].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))
    axes[3, 2].locator_params(axis='y', nbins=5)

    axes[3, 3].plot(res_sup.res_wage_ptcp.drop(['stdev'], axis=1))
    axes[3, 3].set_ylabel('Mean res. wage \n of part. drivers (€)')
    axes[3, 3].set_xlabel('Day')
    axes[3, 3].set_title('(p)')
    axes[3, 3].set_ylim(bottom = 0, top = math.ceil(res_sup.res_wage_ptcp.max().max()*1.2/0.5)*0.5)
    axes[3, 3].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))
    axes[3, 3].locator_params(axis='y', nbins=5)

    axes[4, 0].plot(res_sup.driver_surplus.drop(['stdev'], axis=1))
    axes[4, 0].set_ylabel('Driver surplus (€)')
    axes[4, 0].set_xlabel('Day')
    axes[4, 0].set_title('(q)')
    axes[4, 0].set_ylim(bottom = math.floor(res_sup.driver_surplus.min().min()*0.8/0.5)*0.5, top = math.ceil(res_sup.driver_surplus.max().max()*1.2/0.5)*0.5)
    axes[4, 0].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))
    axes[4, 0].locator_params(axis='y', nbins=5)

    axes[4, 1].plot(res_sup.new_regist.drop(['stdev'], axis=1))
    axes[4, 1].set_ylabel('New daily registrations')
    axes[4, 1].set_xlabel('Day')
    axes[4, 1].set_title('(r)')
    axes[4, 1].set_ylim(bottom = 0, top = math.ceil(res_sup.new_regist.max().max()*1.2/0.5)*0.5)
    axes[4, 1].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))
    axes[4, 1].locator_params(axis='y', nbins=5)

    axes[4, 2].plot(res_sup.new_regist.drop(['stdev'], axis=1))
    axes[4, 2].set_ylabel('Daily deregistrations')
    axes[4, 2].set_xlabel('Day')
    axes[4, 2].set_title('(s)')
    axes[4, 2].set_ylim(bottom = 0, top = math.ceil(res_sup.deregist.max().max()*1.2/0.5)*0.5)
    axes[4, 2].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))
    axes[4, 2].locator_params(axis='y', nbins=5)

    axes[4, 3].plot(res_dem.inform.drop(['stdev'], axis=1))
    axes[4, 3].set_ylabel('Informed travellers')
    axes[4, 3].set_xlabel('Day')
    axes[4, 3].set_title('(s)')
    axes[4, 3].set_ylim(bottom = 0, top = math.ceil(res_dem.inform.max().max()*1.2/0.5)*0.5)
    axes[4, 3].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))
    axes[4, 3].locator_params(axis='y', nbins=5)

    axes[5, 0].plot(res_dem.requests.drop(['stdev'], axis=1))
    axes[5, 0].set_ylabel('Ride-hailing requests')
    axes[5, 0].set_xlabel('Day')
    axes[5, 0].set_title('(t)')
    axes[5, 0].set_ylim(bottom = 0, top = res_dem.requests.max().max() + 50)
    # axes[0, 2].set_ylim(bottom = 0, top = math.ceil(res_scn.requests.max().max()*1.2/50)*50+100)
    axes[5, 0].locator_params(axis='y', nbins=5)

    axes[5, 1].plot(res_dem.gets_offer.drop(['stdev'], axis=1))
    axes[5, 1].set_ylabel('Service rate')
    axes[5, 1].yaxis.set_major_formatter(mtick.PercentFormatter(1))  
    axes[5, 1].set_xlabel('Day')
    axes[5, 1].set_title('(u)')
    axes[5, 1].locator_params(axis='y', nbins=5)

    axes[5, 2].plot((res_dem.perc_wait/60).drop(['stdev'], axis=1))
    axes[5, 2].set_ylabel('Expected waiting time \n of inf. travellers (min)')
    axes[5, 2].set_xlabel('Day')
    axes[5, 2].set_title('(v)')
    axes[5, 2].set_ylim(bottom = 0, top = math.ceil((res_dem.perc_wait/60).max().max()*1.1/1)*1)
    axes[5, 2].set_yticks(np.arange(0, math.ceil((res_dem.perc_wait/60).max().max()*1.1/1)*1+2, step=4))
    axes[5, 2].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))

    axes[5, 3].plot((res_dem.corr_mean_wait/60).drop(['stdev'], axis=1))
    axes[5, 3].set_ylabel('Expected (corrected) \n waiting time of inf. trav. (min)')
    axes[5, 3].set_xlabel('Day')
    axes[5, 3].set_title('(w)')
    axes[5, 3].set_ylim(bottom = 0, top = math.ceil((res_dem.corr_mean_wait/60).max().max()*1.1/1)*1)
    axes[5, 3].set_yticks(np.arange(0, math.ceil((res_dem.corr_mean_wait/60).max().max()*1.1/1)*1+2, step=4))
    axes[5, 3].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))

    axes[6, 0].plot((res_dem.perc_wait_req/60).drop(['stdev'], axis=1))
    axes[6, 0].set_ylabel('Expected waiting time \n of trav. opting for RS (min)')
    axes[6, 0].set_xlabel('Day')
    axes[6, 0].set_title('(x)')
    axes[6, 0].set_ylim(bottom = 0, top = math.ceil((res_dem.perc_wait_req/60).max().max()*1.1/1)*1)
    axes[6, 0].set_yticks(np.arange(0, math.ceil((res_dem.perc_wait_req/60).max().max()*1.1/1)*1+2, step=4))
    axes[6, 0].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))

    axes[6, 1].plot((res_dem.mean_wait/60).drop(['stdev'], axis=1))
    axes[6, 1].set_ylabel('Experienced waiting time (min)')
    axes[6, 1].set_xlabel('Day')
    axes[6, 1].set_title('(y)')
    axes[6, 1].set_ylim(bottom = 0, top = math.ceil((res_dem.mean_wait/60).max().max()*1.1/1)*1)
    axes[6, 1].set_yticks(np.arange(0, math.ceil((res_dem.mean_wait/60).max().max()*1.1/1)*1+2, step=4))
    axes[6, 1].yaxis.set_major_formatter(FormatStrFormatter('%.0f'))

    axes[6, 2].plot(res_dem.bike / (res_dem.requests + res_dem.bike + res_dem.car + res_dem.pt).drop(['stdev'], axis=1))
    axes[6, 2].set_ylabel('Share of travellers \n choosing bike')
    axes[6, 2].yaxis.set_major_formatter(mtick.PercentFormatter(1))  
    axes[6, 2].set_xlabel('Day')
    axes[6, 2].set_title('(z)')
    axes[6, 2].locator_params(axis='y', nbins=5)

    axes[6, 3].plot(res_dem.car / (res_dem.requests + res_dem.bike + res_dem.car + res_dem.pt).drop(['stdev'], axis=1))
    axes[6, 3].set_ylabel('Share of travellers \n choosing private car')
    axes[6, 3].yaxis.set_major_formatter(mtick.PercentFormatter(1))  
    axes[6, 3].set_xlabel('Day')
    axes[6, 3].set_title('(aa)')
    axes[6, 3].locator_params(axis='y', nbins=5)

    axes[7, 0].plot(res_dem.pt / (res_dem.requests + res_dem.bike + res_dem.car + res_dem.pt).drop(['stdev'], axis=1))
    axes[7, 0].set_ylabel('Share of travellers \n choosing public transp.')
    axes[7, 0].yaxis.set_major_formatter(mtick.PercentFormatter(1))  
    axes[7, 0].set_xlabel('Day')
    axes[7, 0].set_title('(ab)')
    axes[7, 0].locator_params(axis='y', nbins=5)

    axes[7, 1].plot(res_dem.vot_inf.drop(['stdev'], axis=1))
    axes[7, 1].set_ylabel('Mean value of time \n of inf. travellers (€/h)') 
    axes[7, 1].set_xlabel('Day')
    axes[7, 1].set_title('(ac)')
    axes[7, 1].set_ylim(bottom = 0, top = math.ceil(res_dem.vot_inf.max().max()*1.1/1)*1)
    axes[7, 1].set_yticks(np.arange(0, math.ceil(res_dem.vot_inf.max().max()*1.1/1)*1+2, step=4))
    axes[7, 1].locator_params(axis='y', nbins=5)

    axes[7, 2].plot(res_dem.vot_req.drop(['stdev'], axis=1))
    axes[7, 2].set_ylabel('Mean value of time \n of trav. opting for RS (€/h)') 
    axes[7, 2].set_xlabel('Day')
    axes[7, 2].set_title('(ad)')
    axes[7, 2].set_ylim(bottom = 0, top = math.ceil(res_dem.vot_req.max().max()*1.1/1)*1)
    axes[7, 2].set_yticks(np.arange(0, math.ceil(res_dem.vot_req.max().max()*1.1/1)*1+2, step=4))
    axes[7, 2].locator_params(axis='y', nbins=5)

    axes[7, 3].plot(res_dem.std_perc_wait.drop(['stdev'], axis=1)/60)
    axes[7, 3].set_ylabel('St. dev. of expected wait \n of inf. travellers (min)') 
    axes[7, 3].set_xlabel('Day')
    axes[7, 3].set_title('(ae)')
    axes[7, 3].set_ylim(bottom = 0, top = math.ceil(res_dem.std_perc_wait.max().max()/60*1.1/1)*1)
    axes[7, 3].set_yticks(np.arange(0, math.ceil(res_dem.std_perc_wait.max().max()/60*1.1/1)*1+2, step=4))
    axes[7, 3].locator_params(axis='y', nbins=5)

    axes[8, 0].plot(res_dem.std_perc_wait_req.drop(['stdev'], axis=1) / 60)
    axes[8, 0].set_ylabel('St. dev. of expected wait \n of trav. opting for RS (min)') 
    axes[8, 0].set_xlabel('Day')
    axes[8, 0].set_title('(af)')
    axes[8, 0].set_ylim(bottom = 0, top = math.ceil(res_dem.std_perc_wait_req.max().max()/60*1.1/1)*1)
    axes[8, 0].set_yticks(np.arange(0, math.ceil(res_dem.std_perc_wait_req.max().max()/60*1.1/1)*1+2, step=4))
    axes[8, 0].locator_params(axis='y', nbins=5)

    axes[8, 1].plot(res_dem.std_exp_wait.drop(['stdev'], axis=1) / 60)
    axes[8, 1].set_ylabel('St. dev. of experienced \n wait time (min)') 
    axes[8, 1].set_xlabel('Day')
    axes[8, 1].set_title('(af)')
    axes[8, 1].set_ylim(bottom = 0, top = math.ceil(res_dem.std_exp_wait.max().max()/60*1.1/1)*1)
    axes[8, 1].set_yticks(np.arange(0, math.ceil(res_dem.std_exp_wait.max().max()/60*1.1/1)*1+2, step=4))
    axes[8, 1].locator_params(axis='y', nbins=5)

    axes[8, 2].plot(res_dem.cons_surplus.drop(['stdev'], axis=1))
    axes[8, 2].set_ylabel('Traveller surplus (€)') 
    axes[8, 2].set_xlabel('Day')
    axes[8, 2].set_title('(ag)')
    axes[8, 2].set_ylim(bottom = math.floor(res_dem.cons_surplus.min().min()*0.9/1)*1, top = math.ceil(res_dem.cons_surplus.max().max()*1.1/1)*1)
    axes[8, 2].set_yticks(np.arange(math.floor(res_dem.cons_surplus.min().min()*0.9/1)*1, math.ceil(res_dem.cons_surplus.max().max()*1.1/1)*1+2, step=4))
    axes[8, 2].locator_params(axis='y', nbins=5)

#     axes[5, 5].plot(res_scn.plf.plat_profit)
#     axes[5, 5].set_ylabel('Platform profit (€)')
#     axes[5, 5].set_xlabel('Day')
#     axes[5, 5].set_title('(ah)')
#     axes[5, 5].set_ylim(bottom = 0, top = math.ceil(res_scn.plf.plat_profit.max().max()*1.1/1)*1)

#     res_scn.soc.tot_value = res_scn.plf.plat_profit + res_sup.driver_surplus + res_dem.cons_surplus
#     axes[6, 0].plot(res_scn.soc.tot_value)
#     axes[6, 0].set_ylabel('Societal value (€)')
#     axes[6, 0].set_xlabel('Day')
#     axes[6, 0].set_title('(ai)')
#     axes[6, 0].set_ylim(bottom = math.floor(res_scn.soc.tot_value.min().min()*0.9/1)*1, top = math.ceil(res_scn.soc.tot_value.max().max()*1.1/1)*1)

    axes[8, 3].plot(res_sup.regist.drop(['stdev'], axis=1) / res_sup.inform.drop(['stdev'], axis=1))
    axes[8, 3].set_ylabel('Share of inf. drivers \n that are registered')
    axes[8, 3].set_xlabel('Day')
    axes[8, 3].set_title('(aj)')
    axes[8, 3].yaxis.set_major_formatter(mtick.PercentFormatter(1)) 

    axes[9, 0].plot(res_sup.particip.drop(['stdev'], axis=1) / res_sup.regist.drop(['stdev'], axis=1))
    axes[9, 0].set_ylabel('Share of reg. drivers \n participating')
    axes[9, 0].set_xlabel('Day')
    axes[9, 0].set_title('(ak)')
    axes[9, 0].yaxis.set_major_formatter(mtick.PercentFormatter(1))
    
    fig.legend(list(res_sup.inform.drop(['stdev'], axis=1).columns), loc='lower center',title=False) #bbox_to_anchor=(0.7, 0.5)
    
    return fig


def plot_single_scenario(res_scn, value):
    fig, axes = plt.subplots(2, 2, figsize = [9,8.4])
    fig.subplots_adjust(hspace=0.8, wspace=0.3)

    axes[0,0].plot(res_scn.sup.inform[value])
    axes[0,0].plot(res_scn.sup.regist[value])
    axes[0,0].plot(res_scn.sup.particip[value])
    axes[0,0].legend(["Informed","Registered", "Participating"],loc='lower center', bbox_to_anchor=(0.5, -0.65),fontsize=14)
    axes[0,0].set_ylabel('Drivers')
    axes[0,0].set_xlabel('Day')
    axes[0,0].set_title('(a)')
    axes[0,0].set_xlim(left = 0, right = 200)

    axes[1,0].plot(res_scn.sup.mean_perc_inc[value])
    axes[1,0].plot(res_scn.sup.mean_exp_inc[value])
    axes[1,0].axhline(y=250,color='gray',linestyle='--')
    axes[1,0].axhline(y=270,color='black',linestyle='--')
    # axes[0, 1].axhline(y=params[scn_id]['drivers']['reservation_wage'],color='gray',linestyle='--')
    axes[1,0].legend(["Expected income","Experienced income","Reservation wage","Total non-operational costs"], loc='lower center', bbox_to_anchor=(0.5, -0.76),fontsize=14)
    axes[1,0].set_xlabel('Day')
    axes[1,0].set_title('(c)')
    axes[1,0].set_ylabel('Average amount (€)')
    axes[1,0].set_ylim(bottom = 0, top = 150)
    axes[1,0].set_xlim(left = 0, right = 200)
    axes[1,0].locator_params(axis='y', nbins=4)

    axes[1,1].plot(res_scn.dem.perc_wait[value]/60)
    axes[1,1].plot(res_scn.dem.corr_mean_wait[value]/60)
    axes[1,1].plot(res_scn.dem.mean_wait[value]/60)
    axes[1,1].legend(["Expected","Experienced (accepted requests)","Experienced (all requests)"], loc='lower center', bbox_to_anchor=(0.5, -0.65),fontsize=14)
    axes[1,1].set_xlabel('Day')
    axes[1,1].set_title('(d)')
    axes[1,1].set_ylabel('Average waiting time (min)')
    axes[1,1].set_ylim(bottom = 0)
    axes[1,1].set_xlim(left = 0, right = 200)
    axes[1,1].locator_params(axis='y', nbins=4)

    axes[0,1].plot(res_scn.dem.inform[value])
    axes[0,1].plot(res_scn.dem.requests[value])
    axes[0,1].plot(res_scn.dem.gets_offer[value] * res_scn.dem.requests[value])
    axes[0,1].legend(["Informed","Rides requested","Requests satisfied"], loc='lower center', bbox_to_anchor=(0.5, -0.65),fontsize=14)
    axes[0,1].set_xlabel('Day')
    axes[0,1].set_title('(b)')
    axes[0,1].set_ylabel('Travellers')
    axes[0,1].set_ylim(bottom = 0)
    axes[0,1].set_xlim(left = 0, right = 200)
    axes[0,1].locator_params(axis='y', nbins=4)
    
    return fig